[build]
  command = "npm run build"
  publish = "build/"

[[redirects]]
  from = “/api/*”
  to = “https://www.swiggy.com/dapi/restaurants/list/v5?lat=12.9621948&lng=77.7115841&page_type=DESKTOP_WEB_LISTING/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
